#!/usr/bin/env bash
# setup-env-docker.sh — write .env.docker from workspace secrets.
#
# Used by docker-compose.dev.yml for the DEEPSEEK_API_KEY / OPENAI_API_KEY
# env vars that the analyze endpoint reads at runtime. The script pulls keys
# from /vol1/@apphome/trim.openclaw/data/workspace/.env.secrets and writes
# them to .env.docker in the repo root. .env.docker is gitignored.
#
# Usage:  bash scripts/setup-env-docker.sh
# Remove: rm .env.docker   (disables LLM-backed analyze in Docker)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SECRETS="/vol1/@apphome/trim.openclaw/data/workspace/.env.secrets"
if [[ ! -f "$SECRETS" ]]; then
  echo "ERROR: $SECRETS not found" >&2
  exit 2
fi

# shellcheck disable=SC1090
set -a; . "$SECRETS"; set +a

OUT=".env.docker"
if [[ -f "$OUT" ]]; then
  echo "  overwriting existing $OUT"
fi

{
  echo "# Generated by scripts/setup-env-docker.sh on $(date -Iseconds)"
  echo "# .env.docker is gitignored — safe to commit existence of the file but"
  echo "# never commit its contents."
  echo "DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}"
  if [[ -n "${OPENAI_API_KEY:-}" ]]; then
    echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
  fi
} > "$OUT"

chmod 600 "$OUT"
echo "✓ wrote $OUT (chmod 600) with $(wc -l < "$OUT") lines"
echo
echo "  docker compose -f docker-compose.dev.yml up -d   # pick up new env"
echo "  curl http://127.0.0.1:8700/health                  # verify"
echo "  curl http://127.0.0.1:8701/                        # verify web"